### ISSUE TITLE
HOT WATER

### ISSUE THREAD

**Issue by sportsandgames** [CitySportsClub/Engineering#102]
Location: Male & Female Locker
Details: No Hot Water

hope we can fix it asap!

thanks

hanna

**Comment by buildingengineers** [comment]
Hello Ms. Hon,

We already contacted the supplier.
They will send their technical to check the unit.
We will feedback soon regarding on the updates of the repair.

Thanks,

Noel

**Comment by sportsandgames** [comment]
Thabk you soo much for the update!
Hope we can fix the soonest. will wait for the update

hanna

**Comment by sportsandgames** [comment]
Hello any update? 

thanks

**Comment by buildingengineers** [comment]
Hello Ms.Hon,

The supplier already purchase the parts of the heater that is damaged. The supplier can't give us the lead time of when the parts will be available since it was ordered from manila, but once it will arrived, they will be scheduling our unit for repair.

Thanks,

Noel

**Comment by buildingengineers** [comment]
Already PR'd back-up heater. Unit will arrived within 2 to 3 weeks.

Thanks.

Noel

**Comment by sportsandgames** [comment]
Hi any update?

thanks

hanna

**Comment by buildingengineers** [comment]
The unit might arrive today.

Thanks,

Noel

**Comment by buildingengineers** [comment]
Hello Ms. Hon,

The new unit arrived yesterday and it is now up and running.

Thanks,

Noel
