### ISSUE TITLE
AIRCON - GYM

### ISSUE THREAD

**Issue by sportsandgames** [CitySportsClub/Engineering#103]
Location: Fitness Gym
Details: init and aircon temperature 27/28 degree, the unit was on @ 545am today.

pls check and monitor.

thanks

hanna

**Comment by buildingengineers** [comment]
Unit will be under observation. Thanks

**Comment by buildingengineers** [comment]
Done AHU cleaning last night.

**Comment by sportsandgames** [comment]
Hi,

any feedback?

thanks

**Comment by buildingengineers** [comment]
Hello Ms. Hon,

We have had adjusted the freon charging of the unit last tuesday. As per observation after the action, there were no complains have been noted.

Thanks,

Noel

**Comment by buildingengineers** [comment]
Hello Ms. Hon,

Since adjusting the freon charge, as per observation, room temperature of the gym is at comfortable level at 25 degrees. Hence we will be now closing this issue.

Thanks.

Noel
