### ISSUE TITLE
CHECK & CLEAN

### ISSUE THREAD

**Issue by sportsandgames** [CitySportsClub/Engineering#111]
Location: B3 // Court A - Locker Area
Details: Dirty , nagbaha

thanks

hanna

**Comment by buildingengineers** [comment]
Hello Ms. Hon,

We will be closing now this issue, as we had talked, water accumulation of dug out is due to clogging of piping system of our storm drain. Repair of the system is for further evaluation since it can cost us large amount of budget.

Thanks.

Noel
