### ISSUE TITLE
CHECK & REPAIR FITNESS GYM

### ISSUE THREAD

**Issue by sportsandgames** [CitySportsClub/Engineering#120]
Location: Fitness Gym // Front Desk Area
Details: Na boslot ang wall behind the front desk

pls. coordinate with the gym attendant

thanks

hanna

**Comment by buildingengineers** [comment]
Will need to schedule repairs, thanks.

**Comment by sportsandgames** [comment]
Any update?

thanks

**Comment by buildingengineers** [comment]
For schedule.

Thanks,

Noel

**Comment by sportsandgames** [comment]
Hi, naka schedule na?

thanks

**Comment by buildingengineers** [comment]
The repair will create noise, odor and dust which will create inconvenience to our members working out. Please advise, what time can we have our repairs. As of today, we are focusing on renovation for florist area.

**Comment by sportsandgames** [comment]
Hi, u said thats for schedule?
anyway, 
FITNESS GYM SCHEDULE
Monday-Friday 6am-9pm
Saturday and Holiday - 7am-7pm
Sunday - 8am-7pm

**Comment by buildingengineers** [comment]
Yes, what I am trying to say is that can we do the repairs during gym operating hours?

**Comment by sportsandgames** [comment]
as u mentioned the repair will create noise and dust so why are going to schedule it during operating hours?

**Comment by buildingengineers** [comment]
Our carpenters work schedule is from 7AM to 4PM.  Nine PM onward might be quite late for work. I was only trying to ask if there is a possibility of working earlier than 9 PM, if there's none then we will have to schedule.

**Comment by buildingengineers** [comment]
Done repairing the wall.

Thanks.

Noel
