### ISSUE TITLE
REPAIR - MEMBERS LOCKER

### ISSUE THREAD

**Issue by sportsandgames** [CitySportsClub/Engineering#124]
Location: Female Locker // (1) Cubicle #3 , (2) hallway
Details: Busted bulb

pls. coordinate w/ Elvisa or any attendant

note: if we can check everything para ma usa og ilis ang busted buld mas maau.

thanks

hanna

**Comment by buildingengineers** [comment]
Done c/o Tech. Bayate.

Thanks.
