### ISSUE TITLE
SUMMER PARTY

### ISSUE THREAD

**Issue by sportsandgames** [CitySportsClub/Engineering#125]
Hi need assistance;

Date: June 9, 2018 Saturday // Time: 1PM
Location: Pool Area
Details: PA System w/ 1 wired mic.
             Background music
             Tech staff to assist
             Steel Barrier

note: Summer Clinic Program Closing Ceremony & CSCC Summer Party

thanks

hanna

**Comment by buildingengineers** [comment]
Hello

Request already noted on the monitoring.

Thanks.

Noel
