### ISSUE TITLE
REQUEST- A BOARD

### ISSUE THREAD

**Issue by sportsandgames** [CitySportsClub/Engineering#127]
Details: 4pcs. A Boards " charged to S&G E-LEAGUE"
            Will need it on June 28, 2018

thanks

hanna

**Comment by buildingengineers** [comment]
Noted. thanks

**Comment by buildingengineers** [comment]
On going fabrication.

Thanks,

Noel

**Comment by buildingengineers** [comment]
Done fabrication of A-Board,ready for deployment at B3 Court.

Thanks,

Noel

**Comment by sportsandgames** [comment]
Thanks much!
