### ISSUE TITLE
CHECK - HOTWATER

### ISSUE THREAD

**Issue by sportsandgames** [CitySportsClub/Engineering#130]
Location: Members Locker
Details: Hotwater not working

have it check asap. and pls give us feedback

thanks

hanna

**Comment by buildingengineers** [comment]
The heater was not able to ignite this morning since there is a soot build up in the pilot. We had the build-up removed and tested. Heater is now running. I already informed Ms. Elvisa this morning on this occurrence. Thanks.

**Comment by buildingengineers** [comment]
Done c/o Tech. Ricky,

Thanks.

Noel
