### ISSUE TITLE
CHECK- ML

### ISSUE THREAD

**Issue by sportsandgames** [CitySportsClub/Engineering#132]
Location: Male Locker // Lounge Area
Details: A.C unit " nagtolo"

pls. coordinate w/ Ken

thanks

hanna

**Comment by buildingengineers** [comment]
The unit was checked by Tech. Adonis.  Unit temp. setting was adjusted to prevent the unit from leaking. As of this time the leaking was controlled. Unit is still under observation.

**Comment by sportsandgames** [comment]
Thank you for the update. 
we will help to monitor.

thanks

**Comment by buildingengineers** [comment]
Thanks.

**Comment by buildingengineers** [comment]
Done cleaning drain pipe of the ACU.
So far. No water dripping was observed.

Thanks.

Noel
