### ISSUE TITLE
REPAIR -B3

### ISSUE THREAD

**Issue by sportsandgames** [CitySportsClub/Engineering#135]
Location: B3 // Multipurpose 2
Details: Busted Light

Pls. coordinate w/ Junar

thanks

**Comment by sportsandgames** [comment]
Any update??

**Comment by buildingengineers** [comment]
For schedule according to availability of the court.

One hour vacant time will do.

Thanks,

Noel

**Comment by sportsandgames** [comment]
Available Time as of today: 
July 23: 7am-4pm
July 24: 12pm-5pm

**Comment by buildingengineers** [comment]
Done replace busted lights c/o Tech. Bayate and Erwin.

Thanks,

Noel
