### ISSUE TITLE
CHECK- MFL AC Unit (14710)

### ISSUE THREAD

**Issue by sportsandgames** [CitySportsClub/Engineering#138]
Location: Female Locker // Locker area
Details: pls check A.C Unit, kay dili bognaw

pls coordinate w/ Elvisa

thanks

**Comment by sportsandgames** [comment]
Any update ?

thanks

**Comment by sportsandgames** [comment]
Any update ?

thanks

**Comment by buildingengineers** [comment]
Filters were cleaned, and settings were adjusted. Under observation.

**Comment by buildingengineers** [comment]
As of this moment. AC is now cold. We'll opened this issue again once the problem still occur.

Thanks,

Noel
