### ISSUE TITLE
MOUNTING OF BANNER

### ISSUE THREAD

**Issue by sportsandgames** [CitySportsClub/Engineering#148]
Location: B3 // Court A
Details: Mounting of banners/ pls. coordinate w/ Hanna

thanks

**Comment by sportsandgames** [comment]
any update?

**Comment by buildingengineers** [comment]
On going fabrication of frame.

Thanks,

Noel

**Comment by sportsandgames** [comment]
Banner is ready for installation.

**Comment by buildingengineers** [comment]
Done installation c/p Teddyboy, Samuel and Tech. Ricky
