### ISSUE TITLE
Repair Laminating Machine

### ISSUE THREAD

**Issue by jskaitor** [CitySportsClub/Engineering#15]
Hi Sir,

Kindly check for repair the laminating machine. Possible to be use tomorrow, 12/14/17. :)

Thanks,
Jen

**Comment by buildingengineers** [comment]
Done repair c/o Tech. Bayate. Machine can now be used again.

**Comment by jskaitor** [comment]
thank you sir

**Comment by buildingengineers** [comment]
​You're welcome miss.​

Thank you very much.

Yours Truly,


*----------- | Building Engineer | City Sports Club Cebu, Inc. *
*Cardinal Rosales Ave., Cebu Business Park, **6000 **Cebu City Philippines *
*P: (6332) 4158700 Local 700 **| **F: (6332) 4158605 **| **M: (63)
09778293606* *|* *E: *bulding.engineer@citysportsclub.com
<mjdhermosisima@citysportsclub.com>
