### ISSUE TITLE
REQUEST- DRIVEWAY 2.0

### ISSUE THREAD

**Issue by sportsandgames** [CitySportsClub/Engineering#163]
Installation of the Tarpaulin

pls. coordinate w/ Hazel or Hanna

thanks

**Comment by buildingengineers** [comment]
Done c/o Teddy, Sam & Tech. Bayate

**Comment by sportsandgames** [comment]
Additional probation. 

already discussed w/ Ricky

**Comment by buildingengineers** [comment]
Done installation of tarpaulin
