### ISSUE TITLE
REPAIR- ASAP ML (14773)

### ISSUE THREAD

**Issue by sportsandgames** [CitySportsClub/Engineering#170]
Location: Male Locker // Shower Area // Cubicle #2 
Details: Detached drainage cover

thanks

**Comment by sportsandgames** [comment]
Any update?

thanks

**Comment by napacana** [comment]
Hi Ms. Han,

Amo ni e.close ha kay naa naman bag.o nga service request unya na.apil naman siya didto.

Thanks.
