### ISSUE TITLE
CSCC ANNIVERSARY- 2018 (2)

### ISSUE THREAD

**Issue by sportsandgames** [CitySportsClub/Engineering#194]
DETAILS: 
1. CHI Side elevator to be closed starting September 11-16
2. Request Samuel to help Chris on September 11&12
3. Request 2 PA System, 1. -B2 elevator area, 2. -B3 parking area (note dry run September 15)
4. Request to cover the B3 Parking area- coordinate w/ Chris where is the location
5. Request Samuel & Teddy Boy to be part of the horror tour staff on the day

**Comment by napacana** [comment]
Done.
