### ISSUE TITLE
FFUP- MML

### ISSUE THREAD

**Issue by sportsandgames** [CitySportsClub/Engineering#195]
Location: Members Female Locker
Details: Follow up on the status of the aircondition switch

**Comment by buildingengineers** [comment]
On going source out of the controller, already PR'd the wire.

**Comment by sportsandgames** [comment]
Thanks.

Estimated days sir na mohoman?

**Comment by buildingengineers** [comment]
Done install air-condition switch. Air-conditioning unit now operational.
