### ISSUE TITLE
SET-UP FOR PRESS FREEDOM RUN - SEPTEMBER 22 SATURDAY

### ISSUE THREAD

**Issue by sportsandgames** [CitySportsClub/Engineering#205]
Location: Upper Ground Floor // Lobby Area
Details: 2 IBM Table w/ 6 chairs // any color of the linen will do
             pls. setup a night prior.

THANKS

**Comment by napacana** [comment]
Hello Ms. Hon,

As per Ops meeting, sila taga Banquet mo set-up ani Ms.

Thanks,

Noel

**Comment by napacana** [comment]
Much better if ato ni e coordinate sa Banquet Captains Ms.

**Comment by sportsandgames** [comment]
Hi sir. Yes, I tag Christel Maymay of F&B :)

thanks

**Comment by napacana** [comment]
Thanks Ms. Han, we will close this issue na ha. Hehe. Thanks.
