### ISSUE TITLE
REPAIR- B3 (14905)

### ISSUE THREAD

**Issue by sportsandgames** [CitySportsClub/Engineering#206]
Location: B3 // Court A
Details: Busted Bulb

pls. Coordinate w/ Junar

thanks

**Comment by sportsandgames** [comment]
Any update?

thanks

**Comment by napacana** [comment]
Hai Ms. Han,

Can i ask the schedule booking of the B3 Court A for this week/month?

Thanks.

**Comment by sportsandgames** [comment]
Available as of Today: October 8, Monday 7am-2pm.

**Comment by napacana** [comment]
Done replacing the busted light as of yesterday.

Thanks.
