### ISSUE TITLE
REQUEST B3- TREASURE BOX

### ISSUE THREAD

**Issue by sportsandgames** [CitySportsClub/Engineering#210]
Already discussed w/ Sir Noel regarding details.
Size: 2ftX6ftX1.5ft

thanks

**Comment by sportsandgames** [comment]
Any update

**Comment by napacana** [comment]
Hi Ms. Han,

We will schedule the fabrication once the materials are available.

Thanks.

**Comment by sportsandgames** [comment]
Hi, Its been 19days ago. wala pa gehapon ang materials?

thanks

**Comment by napacana** [comment]
Done c/o Tech. Aldrin and Lemuel.

Thanks.
