### ISSUE TITLE
CHECK- ML AC UNIT

### ISSUE THREAD

**Issue by sportsandgames** [CitySportsClub/Engineering#214]
Location: Female Locker // Locker Area
Details: Pls check AC unit, we noticed an unusual sound from the unit.

pls. Check asap.

Thanks

**Comment by sportsandgames** [comment]
Any update?

**Comment by napacana** [comment]
Hi Ms. Han,

We pulled out the motor and found out that the bearing has some damaged. We will purchase the bearing today.

Thanks.

**Comment by buildingengineers** [comment]
Done replacement of defective bearing and installation.
