### ISSUE TITLE
REQUEST: B3 (14906)

### ISSUE THREAD

**Issue by sportsandgames** [CitySportsClub/Engineering#219]
Location: B3 // Court B // Court #4 
Details: Busted Bulb

Pls. coordinate w/ Junar

Available Schedule as of today;
Oct. 16- 10am-4pm
Oct. 17- 7am- 4pm
Oct. 18- 10am-2pm
Oct.19- 7am-4pm

thanks

**Comment by buildingengineers** [comment]
Done replacement of Busted Light c/o Tech. Moybel and Adonis
