### ISSUE TITLE
REQUEST- ML

### ISSUE THREAD

**Issue by sportsandgames** [CitySportsClub/Engineering#220]
Location: Members Locker // Entrance Door // Front Desk // Cabinet
Details: Repaint

Thanks

**Comment by buildingengineers** [comment]
This is noted miss, but we have to check first if we can do this during our 2-day shutdown. Thank you for understanding.

**Comment by sportsandgames** [comment]
We can start the liha cguro a week prior the 2-day shutdown para during that day paint nalang ta.
Its been years naman gud nga cgeg request na pa repaint, hope we can do it now.

thanks

**Comment by buildingengineers** [comment]
Mag.paint remover pa ta before magliha miss and mabati jod ana nawng sa door inig strip. The counter and cabinets kay wala ra kaayo tay issue.

**Comment by sportsandgames** [comment]
ok.  unsa man atong angay bohaton?

**Comment by buildingengineers** [comment]
adlaw ra og enough time cguro nga pwede namo matrabaho miss.  isog man gud na og baho man inig tira paint remover unya hugaw kaayo inig strip sa karaan nga pintal. dili sad maapas sa shutdown na trabahuon tanan kay maapektuhan sad among preventive maintenance nga nka.schedule sa kana nga mga adlaw.

**Comment by napacana** [comment]
Hai Ms. Han,

Good day!

Repainting of doors of members locker is to be scheduled this 3Days Holyweek Preventive Maintenance schedule. We will re-opened this issue next year. Thanks

Noel
