### ISSUE TITLE
REQUEST- AC UNIT S&G OFFICE

### ISSUE THREAD

**Issue by sportsandgames** [CitySportsClub/Engineering#229]
Details: Aircon unit maintenance 

thanks

**Comment by buildingengineers** [comment]
Done maintenance of aircon unit

**Comment by sportsandgames** [comment]
pls. double check if it was cleaned. Was advised nga ang aircon cover ra ang na limpyuhan not the filter. 

Thanks

**Comment by buildingengineers** [comment]
Will schedule general cleaning this January 13, 2019

**Comment by buildingengineers** [comment]
The filter was cleaned last time. It just look like that the cover was the one cleaned since it is the one that is pulled out. The filter is attached behind the cover.

**Comment by buildingengineers** [comment]
Done general cleaning of ACU c/o Tech Adonis
