### ISSUE TITLE
Repair - Banquet & LV

### ISSUE THREAD

**Issue by fbservice** [CitySportsClub/Engineering#245]
BANQUET:
1. Repair floor sink (for florist-supplier) near ice machine - drainage clogged - ASAP
2  Door lock of function rooms - Basement 1, UG & 2nd floor ( Nov. 26)
3. Follow-up Blinds in Magallanes (Dec.1)
4. Door lock in All Ante Room Doors (Nov.26)

LA VERANDA:
1.  Repair Cabinet #2 & 3 (replace cabinet lock) (Nov. 26)

**Comment by buildingengineers** [comment]
Done declogging drainage near ice machine c/o Tech Rolhie
Done repair cabinet #2 & 3 c/o Tech Samuel.

**Comment by napacana** [comment]
Hi Ma'am Sha,

We will close this issue na ha, ang magallanes blinds as per discussed sa ops meeting kay ato man to ilisdan na. Pero mangita pa ta ug nindot nga quality nga blinds.

Thanks.
