### ISSUE TITLE
CHECK & REPAIR- B3 REFRIGERATOR (14908)

### ISSUE THREAD

**Issue by sportsandgames** [CitySportsClub/Engineering#254]
Location: B3 // Court A
Details: nanimaho og sunog ang ref. kind check asap

thanks

pls coordinate w/ Bir

**Comment by buildingengineers** [comment]
Done checking and repair c/o Tech. Lemuel. Unit under observation

**Comment by napacana** [comment]
Done c/o Tech. Lemuel.

Thanks
