### ISSUE TITLE
Repair, Cleaning Request & Fabrication

### ISSUE THREAD

**Issue by fbservice** [CitySportsClub/Engineering#260]
La Veranda:
1.) Stainless Buffet Table - for repair (pls. have a recommendation before executing the repair or coordinate with first before doing anything) 
Bistro88:
1.) Chairs/Benches - for vacuum and shampooing - need ASAP
Banquet:
1.) Fabricate - 4 pcs. signage stand (pls coordinate with me for design-specification)

**Comment by napacana** [comment]
Done vacuuming and shampooing and also done fabricate the 4 pc signage.

Thanks.
