### ISSUE TITLE
REPAIR- ML SHOWER DRAIN

### ISSUE THREAD

**Issue by sportsandgames** [CitySportsClub/Engineering#265]
Location: Female Members Locker // Shower areas
Details: Replacement Shower Drain

PLS. COORDINATE W/ ELVISA

THANKS

**Comment by napacana** [comment]
Hai,

As per ops meeting discussion with Sir Rey, we will not replace the shower drain as it is very effective to filter the fallen hairs entering the drain pipe. We will auger all shower drains to unclogged pvc pipes for faster draining.

**Comment by sportsandgames** [comment]
Hi sir Noel, ffup on this.

thanks

**Comment by buildingengineers** [comment]
done replace shower drain at female locker, male locker to follow
