### ISSUE TITLE
MAINTENANCE- AEROBIC ROOM AC UNIT (14866)

### ISSUE THREAD

**Issue by sportsandgames** [CitySportsClub/Engineering#268]
Location: G2 // Aerobic Room
Details: AC unit need cleaning ASAP
 
pls coordinate w/ Edgar

**Comment by buildingengineers** [comment]
Done c/o Tech. Ricky and Adonis.

**Comment by sportsandgames** [comment]
Please check- init napud ang hangin na mugawas sa unit.

pls coordinate w/ Edgar.

**Comment by napacana** [comment]
Done charging the system.

Thanks.
