### ISSUE TITLE
REPAIR- ML BUSTED BULD

### ISSUE THREAD

**Issue by sportsandgames** [CitySportsClub/Engineering#279]
Location: Members Female Locker // Shower Area cubicle #3 
Details: Busted Buld

pls. coordinate w/ Elvisa

Thanks

**Comment by napacana** [comment]
Hi,

For replacement of the socket, from pin type to threaded one.
We will schedule the replacement on non operating hours of the female locker shower.

Thanks.

**Comment by buildingengineers** [comment]
Replaced busted light with spare old pin lights.  We would still replaced the casing and socket into a threaded one.
