### ISSUE TITLE
CHECK&REPAIR- ML SHOWER HOSE

### ISSUE THREAD

**Issue by sportsandgames** [CitySportsClub/Engineering#282]
Location: Members Male Locker // Shower Hose
Details: Leaking shower hose

pls. coordinate w/ Khane

Thanks

**Comment by buildingengineers** [comment]
Done checking, some shower heads needs to be replaced.

**Comment by buildingengineers** [comment]
Done PR of shower heads waiting for delivery

**Comment by sportsandgames** [comment]
Thank you! How long does it take?

**Comment by sportsandgames** [comment]
Additional 2 shower Hose- need replacement. pls check first.

thanks

**Comment by buildingengineers** [comment]
Done replace c/o Tech. Ricky
