### ISSUE TITLE
CHECK&REPAIR-SWIMMING POOL PUMP @ KIDDIE POOL

### ISSUE THREAD

**Issue by sportsandgames** [CitySportsClub/Engineering#292]
Location: Filter Room
Details: Filter Pump Motor @ Kiddie Pool isn't working

pls check ASAP!

Let us know the what happened. Thanks

**Comment by sportsandgames** [comment]
Any update?

**Comment by buildingengineers** [comment]
We already purchased the shaft seal and bearing needed for the repair. We'll give feedback at the end of the day on the status of the repair. Thanks.

**Comment by buildingengineers** [comment]
done repair and re install c/o tech ricky
