### ISSUE TITLE
@ Fitness Gym

### ISSUE THREAD

**Issue by sportsandgames** [CitySportsClub/Engineering#296]
Please check and fix moisture leakage around ventilation above the two Dumbbell Rocks. Asap

Please coordinate with attendant

Thank you!

**Comment by buildingengineers** [comment]
This is noted ma'am, thank you very much.

**Comment by napacana** [comment]
Hi Ms.Han,

Amo sa ni e.close ha, na doble man ang service request. Nag order nasad me materials ani Ms.Han amo ni buhatan ug sandayong.

Thanks.
