### ISSUE TITLE
CHECK&REPAIR- FITNESS GYM

### ISSUE THREAD

**Issue by sportsandgames** [CitySportsClub/Engineering#297]
Location: Fitness Gym // Ceiling- Dumbell Rack Area
Details: Na-ay nagtolo pld check.

Coordinate w/ attendant

thanks

**Comment by buildingengineers** [comment]
This is noted ma'am, thank you very much.

**Comment by napacana** [comment]
On-going works, ceiling repairs to be followed. Thanks.

**Comment by buildingengineers** [comment]
Done repairs

**Comment by sportsandgames** [comment]
Please check ASAP nagtolo napud.

Thanks

**Comment by buildingengineers** [comment]
done repair leaking
