### ISSUE TITLE
La Veranda & FB Office

### ISSUE THREAD

**Issue by fbservice** [CitySportsClub/Engineering#308]
La Veranda-
1. Fabricate and install cabinet cover at cashier area (to cover wiring under cashier POS)

F& B Office-
1. Install - extension/power outlet under my table board

Banquet-
1. Ante Rm 4 - door-jamb almost fall out from wall
2. Install hook for Tarp at the wall of Ballrm3 (wall screen)
3. Wall fan in basement 1 - to move inside storeroom/prep room in basement 1 beside Zula
4.Check electrical outlet inside prep room in basement 1 

Bistro-
1. fabricate a small box for UPS (POS) service area (coordinate with me first)

**Comment by buildingengineers** [comment]
Done transfer of wall fan to prep room.
Done replacement of electrical outlet at prep room.

**Comment by napacana** [comment]
Done install power outlet c/o Tech. Erwin

**Comment by buildingengineers** [comment]
Done repair of door jamb

**Comment by buildingengineers** [comment]
Done fabrication of small box for ups
