### ISSUE TITLE
REPAIR- BUSTED BULB COURT A (14912)

### ISSUE THREAD

**Issue by sportsandgames** [CitySportsClub/Engineering#312]
Location: B3 // Basketball Court A // Bleacher area
Details: Busted Bulb

Pls. coordinate w/ Bir

Thanks

**Comment by buildingengineers** [comment]
This is noted ma'am, we'll schedule. Thanks

**Comment by sportsandgames** [comment]
Additional 1 busted bulb @ court A

**Comment by sportsandgames** [comment]
Any update ?

**Comment by buildingengineers** [comment]
Will schedule the replacement maybe tomorrow.

**Comment by buildingengineers** [comment]
done replace busted bulb c/o tech Ricky
