### ISSUE TITLE
CHECK&REPAIR ASAP- SWIMMING POOL FILTER #3 

### ISSUE THREAD

**Issue by sportsandgames** [CitySportsClub/Engineering#324]
Details: Pump motor na-ay unusual sound. we turned off the filter as of the moment.

pls. coordinate w/ Chris

**Comment by sportsandgames** [comment]
Any update?

**Comment by napacana** [comment]
On-going repairs, motor already pulled out.

**Comment by napacana** [comment]
Done repairs ma'am, motor already installed.
