### ISSUE TITLE
AIRCON FEMALE @ Members Locker

### ISSUE THREAD

**Issue by sportsandgames** [CitySportsClub/Engineering#342]
Please check and repair the aircon at members locker.

Please coordinate w/ attendant

Thank you

**Comment by sportsandgames** [comment]
Any update?

**Comment by napacana** [comment]
Compressor replaced April 01. The unit is under observation for 24 hours.

**Comment by buildingengineers** [comment]
Aircon now running and in good condition. Thanks.
