### ISSUE TITLE
REQUEST- FLAT SCREEN TV (APRIL 7- JUNE12)

### ISSUE THREAD

**Issue by sportsandgames** [CitySportsClub/Engineering#346]
Location: outdoor tennis court
Details: In connection w/ 3point shootout event starting April 7, we will be needing the TV as monitor timer. It will be kept @ S&L office for the mean time.

thanks

**Comment by buildingengineers** [comment]
This is noted, thank you.

**Comment by buildingengineers** [comment]
Done as of April 6, 2019
