### ISSUE TITLE
REPAIR- B3 COURT B

### ISSUE THREAD

**Issue by sportsandgames** [CitySportsClub/Engineering#347]
Location: B3 COURT B
Details: repair of wall nga na buslot

Thanks

**Comment by buildingengineers** [comment]
This is noted. Is B3 court B vacant tomorrow morning?

**Comment by sportsandgames** [comment]
Available sched. nga mejo ta-as 
Tuesday: 7AM-12PM

**Comment by buildingengineers** [comment]
done repair c/o tech Teddyboy, Ricky
