### ISSUE TITLE
CHECK&REPAIR ASAP- FEMALE MEMBERS LOCKER SHOWER#3

### ISSUE THREAD

**Issue by sportsandgames** [CitySportsClub/Engineering#349]
Location: Female Members Locker // Shower Room #3 
Details: Shower Faucet cge og tolo bisan naka lock na.

pls coordinate w/ Elvisa

Thanks

**Comment by buildingengineers** [comment]
done checking, unit for replacement ( materials for PR )

**Comment by buildingengineers** [comment]
done repair c/o tech Aldrin
