### ISSUE TITLE
CHECK&REPAIR- MFL ASAP

### ISSUE THREAD

**Issue by sportsandgames** [CitySportsClub/Engineering#350]
LOCATION: FEMALE LOCKERShower Area Cubicle 2&3
DETAILS: Water Dripping

Please coordinate w/ Khane

Thanks

**Comment by sportsandgames** [comment]
Hi. any update?

**Comment by buildingengineers** [comment]
Hello, fixture for replacement. Currently looking for similar item.

**Comment by buildingengineers** [comment]
Done replacement of new shower head.
