### ISSUE TITLE
REPAIR- ASAP ML

### ISSUE THREAD

**Issue by sportsandgames** [CitySportsClub/Engineering#363]
Location: Male Locker // Cubicle # 4
Details: Check Soap Dispenser

pls coordinate w/ Khane

**Comment by buildingengineers** [comment]
Soap dispenser for replacement

**Comment by sportsandgames** [comment]
Any update?

**Comment by buildingengineers** [comment]
Hello good morning. We are currently purchasing hand foam as replacement to our hand soap dispensers at comfort rooms. As soon as the hand foam dispensers will be delivered, we will install the pulled out hand soap dispensers from the comfort rooms to replace the old and worn-out dispensers at members locker.

**Comment by buildingengineers** [comment]
done replace soap dispenser
