### ISSUE TITLE
CHECK&REPAIR

### ISSUE THREAD

**Issue by sportsandgames** [CitySportsClub/Engineering#364]
Please check and repair the shower area. (Nag cgig tulo)

Pls.coordinate with Lario

Thank you!

**Comment by buildingengineers** [comment]
Hello, is this the one near the pool?

**Comment by sportsandgames** [comment]
Yes, near the pool.

Thanks

**Comment by buildingengineers** [comment]
Done replace shower valve c/o Tech. Ricky
