### ISSUE TITLE
CHECK& REPAIR- A.C UNIT @ MEMBERS LOCKER

### ISSUE THREAD

**Issue by sportsandgames** [CitySportsClub/Engineering#405]
Location: Female Locker // Locker Area
Details: Please check A.C Unit dili bognaw

Already reported to Jef yesterday morning.

Thanks

**Comment by buildingengineers** [comment]
Troubleshoot Aircon
Problem found: Fan Motor Capacitor

**Comment by buildingengineers** [comment]
Done Replace Capacitor for fan motor. Done Troubleshoot. 
AC Status: Operational
