### ISSUE TITLE
SOAP DISPENSER @ MEMBERS LOCKER 

### ISSUE THREAD

**Issue by sportsandgames** [CitySportsClub/Engineering#412]
Location: Members Locker // Shower Room
Details: Soap Dispenser replacement

Please check and replaced asap

Thanks

**Comment by buildingengineers** [comment]
done replace 1 unit at male locker, pending units to follow if stocks arrive

**Comment by buildingengineers** [comment]
Done Replace Soap Dispenser at Male Locker
