### ISSUE TITLE
CHECK&REPAIR- FITNESS GYM A.C UNIT FRONT DESK AREA

### ISSUE THREAD

**Issue by sportsandgames** [CitySportsClub/Engineering#416]
Location: Fitness Gym // Front Desk Area
Details: A.C Power Unit has a weird sound
           Attendant already informed Engr. Moy2x this morning

Please coordinate w/ attendant ASAP

**Comment by buildingengineers** [comment]
done replace fan belt, unit operational, unit under observation c/o tech lemuel
