### ISSUE TITLE
Toilet Bowl water supply cubicle #2

### ISSUE THREAD

**Issue by sportsandgames** [CitySportsClub/Engineering#53]
Please check and fix toilet bowl water supply.

Please coordinate with male Attendant.

Thank you

**Comment by buildingengineers** [comment]
Already checked, will schedule tomorrow miss. thanks

**Comment by buildingengineers** [comment]
Done repair c/o Tech.Ricky

**Comment by sportsandgames** [comment]
Good pm Sir, it was fixed yesterday but today, the problem occurs again as per Locker Attendants. 
Please check. Thank you so much.
