### ISSUE TITLE
Shower Head Holder

### ISSUE THREAD

**Issue by sportsandgames** [CitySportsClub/Engineering#64]
Please check and replace 1 Shower Head Holder cubicle#2 and 1 soap holder at Male Members Locker Room.

Please coordinate with Male Attendant.

Thank you

**Comment by buildingengineers** [comment]
Done replaced shower head holder and 1 soap holder at male cubicle #5&#8.

Thanks,

Noel

**Comment by sportsandgames** [comment]
Thank you!
