### ISSUE TITLE
Request to Switch on and off of our Pool Filters this Holy Week.

### ISSUE THREAD

**Issue by sportsandgames** [CitySportsClub/Engineering#66]
Good afternoon Sir,

We would like to ask for your help to  Switch on and off of our Pool Filters this Holy Week.
Here are the Schedules:

March 29, Thursday - Switch on at 7am by Marlon 
                                - Switch off at 8pm by Engineering/ Security

March 30, Friday     - Switch on at 7am by Engineering/ Security
                                - Switch off at 5pm by Engineering/ Security

March 31, Saturday - Switch on at 7am by Marlon 
                                - Switch off at 8pm by Engineering/ Security

Thank you very much.

**Comment by buildingengineers** [comment]
Done c/o PMD
