### ISSUE TITLE
Damage faucets at Male Comfort Room at Basement 3

### ISSUE THREAD

**Issue by sportsandgames** [CitySportsClub/Engineering#76]
Please check and replace 2 damage faucets at Male Comfort Room at Basement 3.

Thank you.

**Comment by buildingengineers** [comment]
noted miss. thanks

**Comment by sportsandgames** [comment]
Hi. I would like to ff up the status of this request. 

thank you!

**Comment by buildingengineers** [comment]
Hello,

Faucets are not damaged. They are working since it was newly installed last december last year.
As per checking by our personnel, the problem is not on the faucet but on the drain pipes of the faucet that are clogged. It is subject for declogging and it is for scheduled.

Thanks,

Noel

**Comment by sportsandgames** [comment]
Appreciate ur prompt reply sir Noel.
Okay, thanks for the information. May I ask the schedule?  para maka help me og ffup.

thanks!

**Comment by buildingengineers** [comment]
Done auger the P-Trap of the faucet c/o Tech. Bayate
