### ISSUE TITLE
Request - LAN Connection @ B3 for upcoming POS Machine

### ISSUE THREAD

**Issue by Apbasanez** [CitySportsClub/Engineering#804]
Sir Jef, need help in putting a new LAN connection in B3 Basketball Court for the upcoming new POS installation. Will get connection from a2a LAN going to B3. Thanks.

**Comment by Apbasanez** [comment]
HI Sir Jef - I would like to follow-up on the status on this, please. Thank you!

**Comment by buildingengineers** [comment]
Noted on this sir Jun

Thank you very much.
*-jef*
Building Engineer

*CITY SPORTS CLUB CEBU*
Cardinal Rosales St.
Cebu Business Park Cebu City
T: 63 32 4158700 loc 700
F: 63 32 4158603
M: 63 977 829 3606
E: ***@***.***
***@***.***>*
www.citysportscl <http://www.citysportsclub.com/>u
<http://www.citysportsclub.com/>b.com <http://www.citysportsclub.com/>

*"Be Alert. Keep Calm. Think Clearly. Act Decisively "*
