### ISSUE TITLE
SOAP HOLDER - check & repair

### ISSUE THREAD

**Issue by sportsandgames** [CitySportsClub/Engineering#81]
Hi we would like to ask your assistance, pls. see below details;

1. Location: Male locker
               Cubicle # 8
2. Location: Female locker
               Cubicle # 1

thank you

**Comment by buildingengineers** [comment]
what assistance do you need?

**Comment by buildingengineers** [comment]
noted miss, we'll checked the mentioned areas. thanks

**Comment by buildingengineers** [comment]
Done replaced soap holder @ female cubicle #1 and male cubicle #5&#8.

Thanks,

Noel

**Comment by sportsandgames** [comment]
Thanks much sir Noel!
