### ISSUE TITLE
AIRCON UNIT - check & repair (ffup)

### ISSUE THREAD

**Issue by sportsandgames** [CitySportsClub/Engineering#82]
Hi we need your assistance as soon as possible. pls see below details;

Location: Male Locker
               Vanity Area unit

thank you very much, in advance.

**Comment by buildingengineers** [comment]
what assistance do you need?

**Comment by buildingengineers** [comment]
noted miss, we'll checked the unit.  thanks

**Comment by sportsandgames** [comment]
Hi I would like to ffup the status.

thanks

**Comment by buildingengineers** [comment]
Hello Ms. Hon,

The problem on the vanity area aircon is the burnt terminal of the compressor. We'll check if we can still repair, or if not, we will buy new compressor for the aircon.

Thanks,

Noel

**Comment by buildingengineers** [comment]
Hello Ms. Hon, 

The unit is now up and running, we repaired the compressor terminal.

Thanks,

Noel

**Comment by sportsandgames** [comment]
Hi Sir Noel.

Daghan salamat!


hanna
