### ISSUE TITLE
Check & Repair

### ISSUE THREAD

**Issue by sportsandgames** [CitySportsClub/Engineering#83]
Hi. pls see below details;

Location: Females Locker
               Vanity Area
Details: Loosen Soap Holder

Location: Males Locker
Details: Loosen Faucets

thank you!

**Comment by sportsandgames** [comment]
Hi I would like to ffup the status.

thanks

**Comment by buildingengineers** [comment]
Already repaired the soap holder.
Loosen faucets is for scheduled since we dont have the screw that will hold the faucets.

**Comment by buildingengineers** [comment]
Done repair loose faucets.

Thanks,

Noel
