### ISSUE TITLE
AIRCON UNIT -  maintenance (clean)

### ISSUE THREAD

**Issue by sportsandgames** [CitySportsClub/Engineering#84]
Pls. see below details;

Location:  Male locker
                Lounge area
Details: for cleaning (dili na bugnaw)

thank you very much in advance.

**Comment by sportsandgames** [comment]
Hi I would like to ffup the status.

thanks

**Comment by buildingengineers** [comment]
Hello Ms. Hon,

The unit will still trip off even after we have done cleaning it yesterday.
Our maintenance team is still working to solve on this problem.

We will give feedback soon regarding on the updates.

Thanks,

Noel

**Comment by buildingengineers** [comment]
Hello Ms. Hon,

We will be closing this issue. The unit is now operational and the problem did not re occur until this time.

Thanks,

Noel
