### ISSUE TITLE
CHECK & REPAIR - swimming pool

### ISSUE THREAD

**Issue by sportsandgames** [CitySportsClub/Engineering#86]
Location: Swimming Pool
Details: pls check hose (agi-anan sa water to fill the pool)
           - na-ay leak can cause "lomot" sa floor (very dangerous kay dangog kaau)

Note: pls. coordinate to the pool attendant

Hina.ot nga ma gahinan nato og panahon

Salamat

**Comment by buildingengineers** [comment]
Noted Ms. Hon.

**Comment by sportsandgames** [comment]
Hi,

hope you can see me in my office if you have time to discuss this issue.

thanks

hanna

**Comment by sportsandgames** [comment]
Goodmorning

I would like to followup the status on this.

thanks!

**Comment by buildingengineers** [comment]
Done.  We replaced the gate valve. Thanks

**Comment by sportsandgames** [comment]
Thank you
