### ISSUE TITLE
REPAIR - B3 

### ISSUE THREAD

**Issue by sportsandgames** [CitySportsClub/Engineering#87]
Location: B3 Court B
Details: Damage wall / Naboslot ang wall
             
Thanks

**Comment by buildingengineers** [comment]
Noted.

**Comment by sportsandgames** [comment]
Hi
any update?

thanks

hanna

**Comment by buildingengineers** [comment]
For schedule ni Ms. Hon.

Thanks,

Noel

**Comment by buildingengineers** [comment]
Ms. Hon, the repair will be done this July 2 by LJ Partners, the contractor who will repaint the green walls of B3 Court B.

We will be closing this issue na ha?...hehehe :))).

Thanks,

Noel
