### ISSUE TITLE
REQUEST - B3

### ISSUE THREAD

**Issue by sportsandgames** [CitySportsClub/Engineering#88]
Location: B3 Court B Wall
Details: Signage " NO BOUNCING OF BALLS"
            - to prevent nga dili maboslot atong wall-

Thank you!

**Comment by buildingengineers** [comment]
Hello Ms. Hon,

Most of the reasons why mabuslot ang wall is tuyo.on jud nila ug hapak ang wall.
So in this case Ms. Hon, ayo nato ibutang ani is Signage nga nagpahibalo nila nga Bawal nila hapakon ang wall ug tuyo, unya if masakpan sila kay naa mahitabo nila, like penalty ba ron or ma ban sila sa pagsulod na.

Palihug lang nya ko coordinate ni Sir Rey Ms. Hon unsa nga proper wordings sa signage.
Dali raman ni, pwede raman ni ipa laminate man. Hehe.

Thanks,

Noel

**Comment by buildingengineers** [comment]
Hello Ms. Hon,

Can we close now this issue? 
If the signage is made on bond paper and we laminate it then We think this is manageable on your side.
If not made on the bond paper, then maybe the engineering team can help to fabricate the signage.

Thanks,

Noel

**Comment by sportsandgames** [comment]
Hi sir Noel,

Ok, we opt to put a laminated paper nalang as temporary. Will definitely ask your good office an assistance if needed. 

thanks

hanna

**Comment by buildingengineers** [comment]
Hello Ms. Hon,

Since your good office will be the one laminating the signage.
We will be closing this issue Ms. Hon. We will reopened it just in case your office will push through on signage of another material.

Thanks,

Noel
