### ISSUE TITLE
MONITOR

### ISSUE THREAD

**Issue by sportsandgames** [CitySportsClub/Engineering#94]
Hi I would like to ask if we can monitor the aircon @ AEROBICs Room. "dili maka bugnaw"
fyi-
1st incednt was May 4, 530pm-630pm. it happend again today 2pm-3pm.

appreciate your help. for the Club
thank you

hanna

**Comment by buildingengineers** [comment]
We cleaned the air-conditioning unit's filter yesterday evening.  Feel free to feedback us, especially if the "coldness" of the area is still not satisfactory
