### ISSUE TITLE
CHECK & REPAIR- Studio

### ISSUE THREAD

**Issue by sportsandgames** [CitySportsClub/Engineering#95]
Location: B1 //  Studio
Details: Pls. Check aircon near mirror 
         - Im not sure if its a leak, basta naay nagtolo.
         - Natagak ang cover og na bu-ak.

hope we can make action as soon as possible.

thanks

hanna

**Comment by buildingengineers** [comment]
Noted. Thanks.

**Comment by buildingengineers** [comment]
Already PR'd the materials. Will scheduled when the materials will be available.

Thanks,

Noel

**Comment by sportsandgames** [comment]
Thanks for the update!

hanna

**Comment by buildingengineers** [comment]
Done repair c/o Tech. Teddyboy.

Thanks,

Noel
