### ISSUE TITLE
CHECK - B3

### ISSUE THREAD

**Issue by sportsandgames** [CitySportsClub/Engineering#96]
Location: B3 // Court A
Details: Water drops from ceiling
       - (it was noticed by the attendant just today)

pls. check. very dangerous sa mga players.  hope you can give feedback asap.

thanks

hanna

**Comment by buildingengineers** [comment]
Noted. Thanks.

**Comment by buildingengineers** [comment]
Done waterproofing today c/o Tech. Teddy and Tech. Moybel as of 6/4/2018.
