### ISSUE TITLE
REPAIR - B3

### ISSUE THREAD

**Issue by sportsandgames** [CitySportsClub/Engineering#97]
Location: B3 Court A
Details: Change the NET BARRIER// and may i request to install it nga limpyo tanawn. 

Hope we can changed it before the start of eleague. feel free to call us for questions and clarifications.

thanks

hanna

**Comment by buildingengineers** [comment]
On going works, 80% finished.

Thanks,

Noel

**Comment by sportsandgames** [comment]
thumbs up!
