### ISSUE TITLE
B3 - asap

### ISSUE THREAD

**Issue by sportsandgames** [CitySportsClub/Engineering#99]
Location: Court 2, Badminton court B
Details: Nagtolo from ceiling.

Already discussed w/ Ricky. hope we can fix asap.

thanks

hanna

**Comment by buildingengineers** [comment]
We already PR'd the materials for waterproofing of some part of the outdoor tennis court area.
We will scheduled the works once the materials will arrive.

Thanks,

Noel

**Comment by sportsandgames** [comment]
thanks for thwe update!

will wait for the next update.

hanna

**Comment by buildingengineers** [comment]
Done water proofing today c/o Tech. Moybel and Tech. Teddy.
Please do advise us if leaking can be seen after waterproofing.

Thanks.
